# Rosé Pine Palette
# Base: #191724 | Surface: #1f1d2e | Overlay: #26233a
# Text: #e0def4 | Subtle: #908caa | Muted: #6e6a86
# Iris: #c4a7e7 | Rose: #ebbcba | Pine: #31748f | Gold: #f6c177

general {
    no_fade_in = false
    no_fade_out = true
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = ~/.dot/wallpaper.jpg
    color = rgb(25, 23, 36)
    blur_passes = 2
    blur_size = 7
}

# TIME (Gold)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(246, 193, 119)
    font_size = 120
    font_family = Lexend Deca Medium
    position = 0, -200
    halign = center
    valign = top
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(235, 188, 186)
    inner_color = rgb(31, 29, 46)
    font_color = rgb(224, 222, 244)
    fade_on_empty = true
    placeholder_text = 
    hide_input = false
    check_color = rgb(49, 116, 143)
    fail_text = <span foreground="##eb6f92"><i>nope...</i></span>
    fail_color = rgb(235, 111, 146)
    position = 0, -400
    halign = center
    valign = center
}
